// react-app/src/app.tsx
import classNames from 'classnames'
import { useState } from 'react'
import { Outlet } from 'react-router-dom'
import Header from './components/common/header'
import SideNav from './components/common/side-nav'
import { useAuth } from './context/auth-context'
import { useInitialLoad } from './hooks/use-initial-load'

function App() {
  const [showSideNav, setShowSideNav] = useState(true)
  const toggleSideNav = () => {
    setShowSideNav(!showSideNav)
  }
  const { user, userFetched } = useAuth()

  const { isFetching } = useInitialLoad()

  if (isFetching || !userFetched) return <div>Loading</div>
  return (
    <>
      <section className="fixed top-0 right-0 left-0 h-14 bg-blue-500">
        <Header />
      </section>
      <section className=" flex h-screen flex-nowrap pt-14">
        {user?.isAuthenticated ? (
          <aside className={classNames(showSideNav ? 'w-60' : 'w-9', 'max-w-full border-x-2')}>
            <SideNav toggleSideNav={toggleSideNav} showSideNav={showSideNav} />
          </aside>
        ) : null}

        <main className="max-w-full grow basis-0">
          <Outlet />
        </main>
      </section>
    </>
  )
}

export default App

// App/ClientApp/src/app/app.component.ts
import { Component, effect } from '@angular/core';
import { environment } from '../environments/environment';
import { AppUser, AuthUserService } from './security/auth-user.service';
import { LoadingService } from './shared/services/loading.service';
import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  public title = environment.title;
  public loading: boolean = false;
  public user?: AppUser;
  public showSideNav: boolean = true;
  public isSmallScreen: boolean = false;

  constructor(
    private authUserService: AuthUserService,
    private loadingService: LoadingService,
    responsive: BreakpointObserver
  ) {
    this.user = this.authUserService.user;
    effect(() => {
      this.loading = this.loadingService.isLoading();
    });
    responsive.observe([Breakpoints.Small, Breakpoints.XSmall, Breakpoints.Handset]).subscribe((result) => {
      this.isSmallScreen = result.matches;
      this.showSideNav = !result.matches;
    });
  }

  public toggleSideNavCallback() {
    this.showSideNav = !this.showSideNav;
  }
}

<section class="fixed top-0 right-0 left-0 h-14 bg-blue-500">
  <app-header [user]="user"></app-header>
  <header class="border-b-2" *ngIf="user?.isAuthenticated && isSmallScreen">
    <app-side-nav
      [showSideNav]="showSideNav"
      (onToggleSideNav)="toggleSideNavCallback()"
      [isSmallScreen]="isSmallScreen"
    />
  </header>
</section>
<section class="h-screen flex flex-row flex-nowrap" [ngClass]="{ 'pt-24': isSmallScreen, 'pt-14': !isSmallScreen }">
  <div class="absolute right-2 bottom-2">
    <app-notification-alert />
  </div>

  <aside
    *ngIf="user?.isAuthenticated && !isSmallScreen"
    [ngClass]="{ 'w-64': showSideNav, 'w-min': !showSideNav }"
    class="border-x-2 flex-none"
  >
    <app-side-nav
      [showSideNav]="showSideNav"
      (onToggleSideNav)="toggleSideNavCallback()"
      [isSmallScreen]="isSmallScreen"
    />
  </aside>

  <main class="flex-1 overflow-auto">
    <router-outlet></router-outlet>
  </main>
</section>
