// Frontend/angular-app/src/app/app.component.ts
import { Component, effect } from '@angular/core';
import { environment } from '../environments/environment';
import { AppUser, AuthUserService } from './shared/auth-user.service';
import { LoadingService } from './shared/loading.service';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  public title = environment.title;
  public loading: boolean = false;
  public user?: AppUser;

  constructor(
    private authUserService: AuthUserService,
    private loadingService: LoadingService,
    private http: HttpClient
  ) {
    this.user = this.authUserService.user;
    effect(() => {
      this.loading = this.loadingService.isLoading();
    });
  }
}

<section class="fixed top-0 right-0 left-0 h-14 bg-blue-500">
  <app-header [user]="user"></app-header>
</section>
<section class="flex h-screen flex-nowrap pt-14">
  <main className="max-w-full grow basis-0">
    <router-outlet></router-outlet>
  </main>
</section>

// react-app/src/app.tsx
import classNames from 'classnames'
import { useState } from 'react'
import { Outlet } from 'react-router-dom'
import Header from './components/common/header'
import SideNav from './components/common/side-nav'

function App() {
  var [showSideNav, setShowSideNav] = useState(true)

  var toggleSideNav = () => {
    setShowSideNav(!showSideNav)
  }

  return (
    <>
      <section className="fixed top-0 right-0 left-0 h-14 bg-blue-500">
        <Header />
      </section>
      <section className="container flex h-screen flex-nowrap pt-14">
        <aside className={classNames(showSideNav ? 'w-60' : 'w-9', 'max-w-full border-x-2')}>
          <SideNav toggleSideNav={toggleSideNav} showSideNav={showSideNav} />
        </aside>
        <main className="max-w-full grow basis-0">
          <Outlet />
        </main>
      </section>
    </>
  )
}

export default App
