// App/ClientApp/src/app/shared/components/side-nav/side-nav.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import {
  faAnglesLeft,
  faAnglesRight,
  faHouse,
  faFileInvoice,
  faIdCard,
  faDatabase,
} from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-side-nav',
  templateUrl: './side-nav.component.html',
  styleUrls: ['./side-nav.component.css'],
})
export class SideNavComponent {
  @Input({ required: true }) public showSideNav?: boolean;
  @Input({ required: true }) public isSmallScreen?: boolean;
  @Output() public onToggleSideNav = new EventEmitter<void>();

  public faAnglesRight = faAnglesRight;
  public faAnglesLeft = faAnglesLeft;
  public faHouse = faHouse;
  public faFileInvoice = faFileInvoice;
  public faIdCard = faIdCard;
  public faDatabase = faDatabase;
}

<section class="flex flex-col" [ngClass]="{ 'h-full': !isSmallScreen }">
  <section class="flex-auto">
    <nav [ngClass]="{ 'flex flex-wrap justify-evenly': isSmallScreen }">
      <app-nav-link [icon]="faHouse" link="/app/home" linkText="Start page" [showSideNav]="showSideNav" />
      <app-nav-link
        [icon]="faFileInvoice"
        link="/app/orders"
        linkText="Orders & Invoices"
        [showSideNav]="showSideNav"
      />
      <app-nav-link [icon]="faIdCard" link="/app/customers" linkText="Customers" [showSideNav]="showSideNav" />
      <app-nav-link [icon]="faDatabase" link="/app/master-data" linkText="Master data" [showSideNav]="showSideNav" />
    </nav>
  </section>
  <section>
    <div
      *ngIf="!isSmallScreen"
      (click)="onToggleSideNav.emit()"
      class="py-2 flex cursor-pointer items-center justify-start"
      [ngClass]="{ 'px-4': showSideNav, 'px-1': !showSideNav }"
    >
      <span class="w-8 text-center" [ngClass]="{ 'pr-2': showSideNav, 'pr-0': !showSideNav }">
        <fa-icon [icon]="showSideNav ? faAnglesLeft : faAnglesRight" size="lg" />
      </span>
      <span *ngIf="showSideNav">Toggle side menu</span>
    </div>
  </section>
</section>

// react-app/src/components/common/side-nav.tsx
import NavLinks from './nav-links'
import { ChevronDoubleLeftIcon, ChevronDoubleRightIcon } from '@heroicons/react/24/outline'

export default function SideNav({ toggleSideNav, showSideNav }: { toggleSideNav: () => void; showSideNav: boolean }) {
  const className = showSideNav ? 'py-2 px-4' : 'py-2 px-1'
  const iconClassName = showSideNav ? 'w-8 pr-2' : 'w-8 pr-0'
  const text = showSideNav ? <span>Toggle side menu</span> : null
  const icon = showSideNav ? <ChevronDoubleLeftIcon /> : <ChevronDoubleRightIcon />

  return (
    <section className="flex h-full flex-col">
      <section className="flex-auto">
        <NavLinks showSideNav={showSideNav} />
      </section>
      <section onClick={toggleSideNav}>
        <nav>
          <ul>
            <li className={className}>
              <div className="flex cursor-pointer items-center justify-start">
                <span className={iconClassName}>{icon}</span>
                {text}
              </div>
            </li>
          </ul>
        </nav>
      </section>
    </section>
  )
}
